### ISSUE TITLE
Sound Plays but no notification message

### ISSUE THREAD

**Issue by juma929** [phonegap-build/PushPlugin#120]
I am using this plugin and it has always been working fine but recently the push notifications seem to only be playing a sound and no message is coming through.

I am testing on an iOS 7 device and have checked the notification settings etc to ensure they are enabled for the app.

Every time I send, a noise plays no problem, just no text etc.

Thanks for your help!

**Comment by Gp2mv3** [comment]
I've exactly the same issue as you on iOS 7. I followed the example.
In foreground, it works perfectly but in Background, I only have the sound played.
The notification center seems to have registered my app since it's displayed in the list of allowed apps.

Is there a real solution or is it only random ?

Thanks !

**Comment by DharmendraVaishnav91** [comment]
+1 I am facing the same issue. Sound is playing but notification is not showing.
