### ISSUE TITLE
iOS 8 - Register not working?

### ISSUE THREAD

**Issue by jskidd3** [phonegap-build/PushPlugin#312]
I am currently running iOS 8 GM and Xcode 6 GM. When launching the app with the latest version of PushPlugin, it seems that `pushNotification.register` doesn't actually do anything, or at least, neither the success or fail callbacks are called.

Is anyone else facing the same issue?

**Comment by Sanafan** [comment]
Hey Guys and sorry for reoping this closed issue but in my opinion the problem is still persistent. 

I can not register my Device running iOS 8, and compiling via XCode 6.1.1. Plugin-Version is 2.4.0 and after i launched the application, nothing happend. There is just one thing in my console which belongs to the plugin:"Attemping to Badge the application icon but haven't recieved permission from the user to badge the application". This message is correct because the Application is not asking me, if i want to accept push or not. Let me know, if you need code.
