### ISSUE TITLE
Push notification breaks when javascript is obfuscated 

### ISSUE THREAD

**Issue by jvence** [phonegap-build/PushPlugin#572]
We noticed that when we  obfuscate our javascript, push notification breaks. We think the problem lies with the following:
                  pushNotification.register(tokenHandler, errorHandler, {"badge": "true", "sound": "true", "alert": "true", "ecb": "onNotificationAPN"});
where the name of handler functions are passed rather then the actual function. We suspect that The obfuscator is renaming the onNotificationAPN function and is is therefore never found by the plugin. Has anyone experienced similar problems?

**Comment by kaansoral** [comment]
No

There are N obfuscation libraries and methods, choose a different one

Also it's not complicated to inspect the code and see where the problem is

An obfuscation library shouldn't obfuscate global libraries and functions unless it's told to, I haven't seen one that does this, all my function name and variable names stay the same, only the local variables are shortened

**Comment by jvence** [comment]
I am actually using GWT obfuscation and it basically breaks the push notification when obfuscation is enabled. Works fine when it's not. Would it work if we passed the actual function instead of a the name of a function?

**Comment by jvence** [comment]
You are correct. it had to do with a completely separate issue.
