### ISSUE TITLE
Android: icon in system messages is stretched 

### ISSUE THREAD

**Issue by elsigh** [phonegap-build/PushPlugin#82]
In the top bar, the icon looks great, but when you swipe down to see the message the icon is stretched.

**Comment by andreszs** [comment]
@elsigh , exactly where did you place **icon_notification.png** in the folder structure? Inside the *drawable* of the android platform? Because I tried that and didn't work, I still get the default app icon.

I also tried `setSmallIcon(android.R.drawable.noticon)`, with my icon named `noticon.png` in all drawable folders you can possible imagine. Thanks.

**Comment by Heshyo** [comment]
I'm also wondering where to put that icon_notification.png file, and if that works with Phonegap Build?

**Comment by dmonllao** [comment]
@andreszs, you might find this useful 0b422c186a98a8074a944e2bc1e68fad188eb9ee
