### ISSUE TITLE
No notifications in android when the app is closed

### ISSUE THREAD

**Issue by Chexpir** [phonegap-build/PushPlugin#85]
In GCMIntentService.java:73 we see they check if the app is in foreground

// Send a notification if there is a message and not in foreground
            if (!PushPlugin.isInForeground() && extras.getString("message").length() != 0) {

, but that #79 change doesn't work correctly in android due to the ActivityManager starts the app in the moment the notification is received, thus when the app is completely closed there is no notification.

10-08 11:56:16.042: I/ActivityManager(525): Start proc com.myapp.mainClass for broadcast com.myapp.mainClass/com.plugin.gcm.CordovaGCMBroadcastReceiver: pid=25076 uid=10112 gids={50112, 3003, 1028}
10-08 11:56:16.072: V/GCMBroadcastReceiver(25076): onReceive: com.google.android.c2dm.intent.RECEIVE
10-08 11:56:16.072: V/GCMRegistrar(25076): Setting the name of retry receiver class to com.plugin.gcm.CordovaGCMBroadcastReceiver
10-08 11:56:16.072: V/GCMBroadcastReceiver(25076): GCM IntentService class: com.plugin.gcm.GCMIntentService
10-08 11:56:16.082: V/GCMBaseIntentService(25076): Acquiring wakelock
10-08 11:56:16.082: V/GCMBaseIntentService(25076): Intent service name: GCMIntentService-GCMIntentService-1
10-08 11:56:16.092: D/GCMIntentService(25076): onMessage - context: android.app.Application@41dce920
10-08 11:56:16.092: V/PushPlugin(25076): sendExtras: caching extras to send at a later time.
10-08 11:56:16.092: D/GCMIntentService(25076): onMessage - foreground: true
10-08 11:56:16.092: D/GCMIntentService(25076): onMessage - message: ? Peace,Love ? and PhoneGap ?!
10-08 11:56:16.092: V/GCMBaseIntentService(25076): Releasing wakelock

**Comment by RMarietta** [comment]
I'm encountering the same issue:
1. Using PGB to build the app (3.6.3)
2. Android device does not display notification after force quit (app is not running in background)

I've read through all the comments here... I tried using a title and message in the push notification and have delay_while_idle set to false and the notification still does not get displayed.

Was anyone able to get this to work?

**Comment by marie-dk** [comment]
@RMarietta Cordova 4.2 with plugin 2.4 on Android 4.4.2 ... Same thing here... receiving nothing when the app is closed. I tried delay_while_idle with both true and false... it had no effect. As @nvcken said, it is not clear where to set this value. I found a php gcm script to send messages where this value can be set: http://www.go4expert.com/articles/send-android-push-notifications-using-t29896/ (in the $fields array). But I have no idea where to set this value when using pubnub javascript or php script.

But either way, setting delay_while_idle and a message title, had no effect.

**Comment by celwell** [comment]
Make sure you are sending a JSON payload with the correct format. Send a raw default message will only work when app is in foreground.

`
{
   "GCM":"{
      "data":{
         "message":"Check out these awesome deals!"
      }
   }"
}
`

**Comment by shprink** [comment]
@celwell I followed your format and it is the same only works with foreground.

```
{
    "event": "message",
    "from": "219209889674",
    "collapse_key": "push",
    "foreground": true,
    "payload": {
        "GMC": {
            "data": {
                "id": 0,
                "message": "This is a test notification"
            }
        }
    }
}
```

**Comment by shprink** [comment]
Made it work like this:

{
    "event": "message",
    "from": "219209889674",
    "collapse_key": "push",
    "foreground": true,
    "payload": {
         "message": "This is a test notification"
    }
}

**Comment by celwell** [comment]
You wrote "GMC" instead of "GCM".

**Comment by shprink** [comment]
@celwell Yeah good catch, nervermind, I found that the message key is Mandatory, if it not present than no push notifications others than foreground.

**Comment by aorylamballe** [comment]
Hi,

My project has the same issue as reported in this topic. We receive the notifications when:
- The app is in foregroud (calling callback function)
- The app is in background (in status bar, but no call to the callback function, even after the app is open)
- With phone open and sleeping/locked

But **the notifications are never received if the application is completely closed** (slide up the app in the list of opened apps, or restart phone).

I tried to always display notifications/call callback function in the root of ```GCMIntentService.onMessage``` to check whether the problem is in this function. But ```onMessage``` is never called when the application is completely closed. It seems to be the cause, since it contains the code to trigger the notification.

Recent suggestions does not seem to apply or help:
- **delay_while_idle** is for the case when we don't receive the notification with locked screen (but I receive it, as long as the app is opened, background or foreground)
- The **message** and **title** keys are present in the notification. Below is the content of the event object received in the callback function (which reflects the content of the notification received):
``` javascript
{
	collapse_key : "do_not_collapse",
	event : "message",
	foreground : true,
	from : "123456789012",
	message : "Some notification text",
	msgcnt : "8",
	payload : {
		message : "Some notification text",
		msgcnt : "8",
		title : "My notification"
	}
}
```

Any idea about how to fix it?

Since I am not the only one with this issue, I guess it should be reopened.

Thanks!

**Comment by aorylamballe** [comment]
I answer my own question after some investigation, in case someone has the same issue.

My issue was because I have a Xiaomi phone with MIUI as OS. It embeds a feature to forbid apps to run in background if not allowed in a whitelist ([Detailed explanation](http://en.miui.com/thread-117992-1-1.html)).

**Solution:** allow the app to auto-start in Security Center app > Permissions > Autostart > switch on your app

I was confused because apps like Wechat (chinese Whatsapp) and Google were already working. Wechat was already allowed, and Google... maybe because it is sync (settings/accounts...).

Android 4.4.1 and 4.4.2 had [an issue with the same behavior](http://www.androidpolice.com/2014/03/07/bug-watch-stopping-apps-on-android-4-4-2-can-silently-kill-related-background-services-a-fix-is-on-the-way/), but it seems to be fixed in 4.4.4.

**Comment by abhinavgujjar** [comment]
@aorylamballe Thanks so much for posting this information. I just checked on an Nexus phone and the notifications come in even when the app is closed

**Comment by apolkingg8** [comment]
@aorylamballe You save my days! :beer:

**Comment by mfkenson** [comment]
@aorylamballe You save my days! +1
mine is asus zenfone2 with auto-startup manager (this stupid security app also disable notifications from my app by default..)

**Comment by PaulCannell** [comment]
So Ive used this plugin before about a year ago. Then today I create a new ionic project and I get my notification in code on the device but I dont get a notification in the android header bar (where the whatsapp icon shows when you have new / unread messages) Im also not getting any messages if the app is in the background. 
Cordova version 6.0.0
com.phonegap.plugins.PushPlugin 2.5.0

Any ideas?

**Comment by macdonst** [comment]
@PaulCannell switch to https://github.com/phonegap/phonegap-plugin-push. I'm maintaining that one and the Ionic guys are helping out as well.

**Comment by PaulCannell** [comment]
Legend. So much easier. Up and running already Tx
